### ISSUE TITLE
I hava some question about npm....

### ISSUE THREAD

**Issue by terminalqo** [Kikobeats/react-clap-button#17]
I'm newbie, I just wonder why this package`s  folder structure in node_modules is totally different from github ?

**Comment by Kikobeats** [comment]
Hello, I only export the useful files at npm registry to reduce the bundle size to be downloaded by the user:
https://github.com/Kikobeats/react-clap-button/blob/master/package.json#L63

lib is the compiled version of the library to be ES5+ compatible 🙂

**Comment by terminalqo** [comment]
@Kikobeats Yes! I figure it out! Because of `package.json.files` keyword ! Thanks!!

**Comment by terminalqo** [comment]
I found [Babel React Optimize](https://github.com/jamiebuilds/babel-react-optimize). Which use the same 4 packages in your `.babelrc.env.production.plugins` , But version is too old...

**Comment by Kikobeats** [comment]
what do you mean?

**Comment by terminalqo** [comment]
Never mind, haha, I'm just learning your code.. ，curious about your `.babelrc`.`env`.`production`.`plugin` array. I mean , There is already a `presets: ["react"]` ，why add these "transform-react-plugins" in `env.production.plugins`. And I google it , it's used to optimize React...
