### ISSUE TITLE
react-clap-buttton is not properly namespaced

### ISSUE THREAD

**Issue by nfedyashev** [Kikobeats/react-clap-button#33]
Hi @Kikobeats 

first of all thanks for the react-clap-button!
I've experienced an issue when one need to display several react-clap-buttons on one page.
In this case it becomes unfunctional - animation, counters, styling.

Unfortunately I'm in hurry right now. If anyone has some time to fix it properly here's some context info:

mojs configuration has static(non namespaced) settings(*el:* and "parent:")
Same with ClapButton's, ClapIcon's, ClapCount's and ClapCountTotal's ids.
It's all localised in one file - src/index.js

**Comment by Kikobeats** [comment]
Can you make your error reproducible using [codesandbox](https://codesandbox.io)?
