### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by adjwills** [Kikobeats/react-clap-button#45]
Following basic usage outlined, i.e. install package
```
npm install react-clap-button --save
```
and then importing `ClapButton`
```
import ClapButton from 'react-clap-button';
```
Creates error
```
Module not found: Can't resolve 'react-clap-button'
```

Looks like the module is missing the src files upon installation? I did it with a fresh CRA react app, and got the same issue.

**Comment by Kikobeats** [comment]
Hello, that's because `main` is referenced in the compiled version of the source code.

It should be fixed after add `postinstall` script.

Can you confirm to me if `v1.1.4` is working fine for you?

**Comment by adjwills** [comment]
Hey, no worries. 

Same issue for `v1.1.4` and `v1.1.3` it seems. However, `v.1.1.2` and below seem to work

**Comment by Kikobeats** [comment]
`v.1.12` is exporting `main` `lib/index.js` and this file doesn't exit in the zip I downloaded 🤔

**Comment by Kikobeats** [comment]
Can you try to edit `main` file manually? maybe could be a thing related of what code bundler are you using?

**Comment by adjwills** [comment]
Testing this on a create-react-app install using webpack, have tried installing with `yarn` and `npm`. Still no joy for now.
