### ISSUE TITLE
Add option for "max clicks"

### ISSUE THREAD

**Issue by breadadams** [Kikobeats/react-clap-button#5]
Not sure if included/planned already, but would be neat to add a way to lock the _max clicks_ each user can make.

**Comment by Kikobeats** [comment]
Yes, it's `50`, but need to move the value as defaultProp:

https://github.com/Kikobeats/react-clap-button/blob/master/src/index.js#L168

**Comment by breadadams** [comment]
Aha, good point. Although it's not _totally_ blocking clicks, as `countTotal` still increments.

eg.
![react-clap-over-50](https://user-images.githubusercontent.com/5795227/36496264-07f03fb2-1738-11e8-904c-1c5aa57ddbbe.gif)
